<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Both strings are matching]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="138" started-at="2019-06-26T11:09:54Z" finished-at="2019-06-26T11:09:54Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="138" started-at="2019-06-26T11:09:54Z" finished-at="2019-06-26T11:09:54Z">
      <class name="framework_testng.Assert_Reports">
        <test-method status="FAIL" signature="tc001()[pri:0, instance:framework_testng.Assert_Reports@5419f379]" name="tc001" duration-ms="39" started-at="2019-06-26T16:39:54Z" finished-at="2019-06-26T16:39:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Signin] but found [Signi]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Signin] but found [Signi]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at framework_testng.Assert_Reports.tc001(Assert_Reports.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc001 -->
        <test-method status="PASS" signature="tc002()[pri:0, instance:framework_testng.Assert_Reports@5419f379]" name="tc002" duration-ms="6" started-at="2019-06-26T16:39:54Z" finished-at="2019-06-26T16:39:54Z">
          <reporter-output>
            <line>
              <![CDATA[Both strings are matching]]>
            </line>
          </reporter-output>
        </test-method> <!-- tc002 -->
      </class> <!-- framework_testng.Assert_Reports -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
